name: Build and release binaries
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'

jobs:
  dummy-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 1
  dummy-1-arm:
    runs-on: ubuntu-latest
    steps:
      - run: echo 1

  build-final:
    needs: dummy-1
    if: ${{ !cancelled() && !failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download prebuilt helium-x86_64
        uses: actions/download-artifact@v4
        with:
          name: helium-x86_64
          # Using the official API to download from another workflow run
          run-id: 16860058038
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: helium-x86_64

      - name: Upload helium-x86_64
        uses: actions/upload-artifact@v4
        with:
          name: helium-x86_64
          path: helium-x86_64

  build-arm-final:
    needs: dummy-1-arm
    if: ${{ !cancelled() && !failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download prebuilt helium-arm64
        uses: actions/download-artifact@v4
        with:
          name: helium-arm64
          run-id: 16860058038
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: helium-arm64

      - name: Upload helium-arm64
        uses: actions/upload-artifact@v4
        with:
          name: helium-arm64
          path: helium-arm64

  publish-release:
    needs: [build-final, build-arm-final]
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: helium-x86_64
      - name: Download arm package
        uses: actions/download-artifact@v4
        with:
          name: helium-arm64
      - name: Publish release
        id: publish
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            helium*
    outputs:
      assets: ${{ steps.publish.outputs.assets }}

